# site-wide variables
title: Awesome Lab
email: jane.smith@gmail.com
google: jane smith
github: awesomelab
twitter: awesomelab
instagram: awesomelab

# base directory where site is hosted
baseurl: "/lab-website-template"

# default front matter parameters
defaults:
  - scope:
      path: ""
    values:
      layout: default
      background: images/test-tube.jpg
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "posts"
    values:
      layout: post

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
