- id: doi:10.17504/protocols.io.bhx8j7rw
  image: images/genomic_DNA_gel.jpg
  tags: 
    - DNA extraction
    - genome

- id: pmid:33607033
  image: https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/4f6a7310-bc2d-4083-823f-f131655ab9cf/fx1.jpg
  tags:
    - phylogeny
- id: pmid:33547391
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7865070/bin/41598_2021_82607_Fig2_HTML.jpg
  tags:
    - phylogeny
    - olpidium
    - metagenome

- id: pmid:32900807
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7482067/bin/mBio.02027-20-f0003.jpg
  tags:
    - mycovirus

- id: pmid:30639767
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/6886740/bin/nihms-1060063-f0001.jpg
  tags:
    - Zoopagomycota
    - phylogeny

- id: pmid:30485448
  image: https://nph.onlinelibrary.wiley.com/cms/asset/524a802a-57d1-4e90-8bcd-201384172d4e/nph15613-fig-0001-m.jpg
  tags:
    - Endogone
    - metagenome

- id: pmid:28917057
  image: https://journals.asm.org/cms/10.1128/microbiolspec.FUNK-0053-2016/asset/11cb3c3e-c2ec-4642-a78b-cab4ecf7bbec/assets/graphic/funk-0053-2016-fig1.gif
  tags:
    - phylogeny

- id: pmid:34472169
  tags:
    - Cenococcum

- id: pmid:33538380
  tags:
    - wood decay
    - rot
- id: pmid:33118170
  tags:
    - desert truffle

- id: pmid:33046698
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/7550596/bin/41467_2020_18795_Fig4_HTML.jpg
  tags:
    - mycorrhizal
    - ECM
- id: pmid:31621176
  tags:
    - AMF
    - Gigaspora
    - genome

- id: pmid:31337355
  tags:
    - lichen
    - genome
    - Cladonia

- id: pmid:30886374
  tags: 
    - mushroom
    - genome

- id: pmid:30636349
  tags:
    - AMF
    - genome
    - comparative genomics

- id: pmid:30420746
  tags:
    - truffle
    - Pezizomycetes
    - genome

- id: pmid:29355972
  tags:
    - AMF
    - Rhizophagus

- id: pmid:29315638
  tags: 
    - mycorrhizal
    - ericoid 


