name: Update research data

on:
  pull_request:
    paths:
      - "_data/research-input.yml"

jobs:
  update_research:
    name: Update Manubot-generated citations in research data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Manubot
        run: pip install --upgrade manubot
      - name: Build updated research output file
        run: python _data/build-research.py
      - name: Commit new research output file
        uses: EndBug/add-and-commit@v5
        with:
          add: "_data/research-output.yml"
          message: "update Manubot-generated citations in research data"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
